import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { PGlite } from '@electric-sql/pglite';

const stage1 = readFileSync(new URL('../../../supabase/migrations/202609290001_dashboard_memberships.sql', import.meta.url), 'utf8');
const stage2 = readFileSync(new URL('../../../supabase/migrations/202609290002_private_data_cutover.sql', import.meta.url), 'utf8');
const userA = '00000000-0000-0000-0000-000000000001';
const userB = '00000000-0000-0000-0000-000000000002';
const viewer = '00000000-0000-0000-0000-000000000003';

// A representative Supabase schema with intentionally permissive legacy policies.
// Tests execute the actual migration SQL, not a JS imitation of RLS.
test('membership RLS and private-data cutover enforce real Postgres access', async (t) => {
  const db = new PGlite();
  await db.exec(`
    create role anon; create role authenticated; create role service_role bypassrls;
    create schema auth; create schema storage;
    grant usage on schema public, auth, storage to anon, authenticated, service_role;
    create table auth.users(id uuid primary key);
    create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
    create table public.organizations(id bigint primary key, org text);
    create table storage.objects(id bigint generated by default as identity primary key, bucket_id text, name text);
    alter table storage.objects enable row level security;
    grant all on storage.objects to anon, authenticated;
    grant usage on all sequences in schema storage to anon, authenticated;
    create policy legacy_storage_all on storage.objects for all to public using (true) with check (true);
    insert into auth.users values ('${userA}'), ('${userB}'), ('${viewer}');
    insert into public.organizations values (9, 'Rescue A'), (10, 'Rescue B');
    grant all on public.organizations to public;
    create policy legacy_org_all on public.organizations for all to public using (true) with check (true);
  `);
  for (const table of ['animals', 'applications', 'form_submissions', 'website_content', 'branding', 'policies', 'events', 'donations']) {
    await db.exec(`create table public.${table}(id bigint generated by default as identity primary key, org_id bigint not null, name text); grant all on public.${table} to public; create policy legacy_all on public.${table} for all to public using(true) with check(true); insert into public.${table}(org_id,name) values (9,'A'),(10,'B');`);
  }
  await db.exec(stage1);
  await db.exec(`insert into public.organization_memberships(user_id,org_id,role) values ('${userA}',9,'staff'),('${userB}',10,'owner'),('${viewer}',9,'viewer');`);
  const as = async (role, userId, sql) => {
    await db.exec(`reset role; set role ${role}; select set_config('request.jwt.claim.sub', '${userId ?? ''}', false);`);
    try { return await db.query(sql); } finally { await db.exec('reset role'); }
  };

  await t.test('member reads only own animals despite old USING(true) policy', async () => {
    const result = await as('authenticated', userA, 'select org_id from public.animals order by org_id');
    assert.deepEqual(result.rows, [{ org_id: 9 }]);
    const orgs = await as('authenticated', userA, 'select id from public.organizations');
    assert.deepEqual(orgs.rows, [{ id: 9 }]);
  });
  await t.test('cross-organization inserts and updates are denied', async () => {
    await assert.rejects(as('authenticated', userA, "insert into public.animals(org_id,name) values (10,'intruder')"), /row-level security/i);
    assert.equal((await as('authenticated', userA, "update public.animals set name='hacked' where org_id=10 returning id")).rows.length, 0);
  });
  await t.test('staff writes own animals but cannot change organization settings', async () => {
    assert.equal((await as('authenticated', userA, "update public.animals set name='edited' where org_id=9 returning id")).rows.length, 1);
    assert.equal((await as('authenticated', userA, "update public.organizations set org='hacked' where id=9 returning id")).rows.length, 0);
    await assert.rejects(as('authenticated', userA, "insert into public.branding(org_id,name) values(9,'hacked')"), /row-level security/i);
  });
  await t.test('viewer reads but cannot write or promote themselves', async () => {
    assert.equal((await as('authenticated', viewer, 'select id from public.animals')).rows.length, 1);
    assert.equal((await as('authenticated', viewer, "update public.animals set name='viewer write' where org_id=9 returning id")).rows.length, 0);
    await assert.rejects(as('authenticated', viewer, "insert into public.animals(org_id,name) values(9,'viewer')"), /row-level security/i);
    await assert.rejects(as('authenticated', viewer, "update public.organization_memberships set role='owner' where user_id=auth.uid()"), /permission denied/i);
  });
  await t.test('memberships are visible only to the matching user', async () => {
    const result = await as('authenticated', userA, 'select user_id,org_id from public.organization_memberships');
    assert.deepEqual(result.rows, [{ user_id: userA, org_id: 9 }]);
    await assert.rejects(as('anon', null, 'select * from public.organization_memberships'), /permission denied/i);
  });
  await t.test('owner can edit own settings; authenticated table truncate is denied', async () => {
    assert.equal((await as('authenticated', userB, "update public.organizations set org='Rescue B updated' where id=10 returning id")).rows.length, 1);
    await assert.rejects(as('authenticated', userB, 'truncate public.animals'), /permission denied/i);
  });
  await t.test('org ownership stays immutable even for a member of both organizations', async () => {
    await db.exec(`insert into public.organization_memberships(user_id,org_id,role) values ('${userA}',10,'staff');`);
    await assert.rejects(as('authenticated', userA, 'update public.animals set org_id=10 where org_id=9'), /ownership cannot be changed/i);
    await db.exec(`delete from public.organization_memberships where user_id='${userA}' and org_id=10;`);
  });
  await t.test('revocation takes effect on the next database request', async () => {
    await db.exec(`update public.organization_memberships set is_active=false where user_id='${userA}';`);
    assert.equal((await as('authenticated', userA, 'select * from public.animals')).rows.length, 0);
    await assert.rejects(as('authenticated', userA, "insert into public.animals(org_id,name) values(9,'revoked')"), /row-level security/i);
    await db.exec(`update public.organization_memberships set is_active=true where user_id='${userA}';`);
  });
  await t.test('Storage upload path must match an editable membership', async () => {
    await as('authenticated', userA, "insert into storage.objects(bucket_id,name) values('animal-images','9/photos/a.jpg')");
    await assert.rejects(as('authenticated', userA, "insert into storage.objects(bucket_id,name) values('animal-images','10/photos/hacked.jpg')"), /row-level security/i);
    await assert.rejects(as('authenticated', viewer, "insert into storage.objects(bucket_id,name) values('animal-images','9/photos/viewer.jpg')"), /row-level security/i);
    await assert.rejects(as('authenticated', userA, "insert into storage.objects(bucket_id,name) values('animal-images','invalid/photos/a.jpg')"), /row-level security/i);
  });
  await t.test('Stage 1 preserves existing anon site reads; Stage 2 revokes them', async () => {
    assert.equal((await as('anon', null, 'select * from public.animals')).rows.length, 2);
    await db.exec('grant select (id, org_id, name) on public.applications to anon');
    await db.exec(stage2);
    await assert.rejects(as('anon', null, 'select * from public.animals'), /permission denied/i);
    await assert.rejects(as('anon', null, 'select * from public.applications'), /permission denied/i);
    await assert.rejects(as('anon', null, "insert into storage.objects(bucket_id,name) values('animal-images','9/photos/anon.jpg')"), /row-level security/i);
    assert.equal((await as('authenticated', userA, 'select * from public.animals')).rows.length, 1);
  });
  await db.close();
});
